# 切片

In [1]:
import numpy as np

In [2]:
arr=np.arange(10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[5]

5

In [5]:
arr[5:9]

array([5, 6, 7, 8])

In [9]:
arr[5:9]=12#对切片进行赋值会对原数组进行改变

In [10]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

对数组的切片操作和对列表的操作没有什么区别，如果需要提取一部分数据进行操作的话，可以使用显式的.copy()方法

# 索引

数组通常是二维以上的，所以对数组的索引可以借助坐标图来表示，首先定位x轴，然后再定位y，z

In [16]:
arr1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [17]:
arr1

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

这是一个2*2*3的数组，定位时首先定位行，之后是列

In [19]:
arr1[:2,1:]

array([[[ 4,  5,  6]],

       [[10, 11, 12]]])

In [20]:
arr1[:1,1:,:2]

array([[[4, 5]]])

# 布尔索引

有时需要对符合某种条件的列表操作，这个时候就需要将它们全都提取出来

In [21]:
names=np.array(['bob','joe','will','bob','will','joe','joe'])

In [23]:
data=np.random.randn(7,4)

In [24]:
data

array([[ 0.25916272,  1.63630311,  0.32949768, -0.46096477],
       [-0.59557257, -1.98197873, -1.85296647,  0.42315679],
       [ 0.87570345, -0.42605906,  0.99298767,  0.61967051],
       [-0.5897261 , -1.62444358, -1.96198563, -0.59568305],
       [ 1.44393488, -0.66361183,  0.81835936,  0.63564538],
       [-0.12876959,  1.00718987,  0.64833864,  0.32753034],
       [-1.18716613, -0.10223804, -0.07479304, -0.31164969]])

names是一维列表，对应data中的行

In [26]:
names=='joe'

array([False,  True, False, False, False,  True,  True])

这个时候就会变成一个布尔值列表

In [27]:
data[names=='joe']

array([[-0.59557257, -1.98197873, -1.85296647,  0.42315679],
       [-0.12876959,  1.00718987,  0.64833864,  0.32753034],
       [-1.18716613, -0.10223804, -0.07479304, -0.31164969]])

就可以把joe对应的行提取出来了

当然也可以使用多个条件进行提取。
使用&（and）和|（or）来代替，python中的and 和 or 对布尔值列表没用

In [29]:
mask=(names=='bob')|(names=='will')

In [30]:
mask

array([ True, False,  True,  True,  True, False, False])

In [32]:
data[mask]

array([[ 0.25916272,  1.63630311,  0.32949768, -0.46096477],
       [ 0.87570345, -0.42605906,  0.99298767,  0.61967051],
       [-0.5897261 , -1.62444358, -1.96198563, -0.59568305],
       [ 1.44393488, -0.66361183,  0.81835936,  0.63564538]])

也可以使用常识设置布尔值

In [33]:
data[data<0]=0

In [34]:
data

array([[0.25916272, 1.63630311, 0.32949768, 0.        ],
       [0.        , 0.        , 0.        , 0.42315679],
       [0.87570345, 0.        , 0.99298767, 0.61967051],
       [0.        , 0.        , 0.        , 0.        ],
       [1.44393488, 0.        , 0.81835936, 0.63564538],
       [0.        , 1.00718987, 0.64833864, 0.32753034],
       [0.        , 0.        , 0.        , 0.        ]])

# 神奇索引：使用整数数组进行数据索引

In [35]:
arr=np.empty((8,4))

In [36]:
for i in range(8):
    arr[i]=i

In [37]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [38]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

如果使用负数索引，则从尾部进行选择

In [40]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

神奇索引可以用来矩阵切片，并且是对数据的复制，对其改变不会对原数组改变