# 生成数组

In [2]:
import numpy as np

In [3]:
data1=[6,7.5,8,0,1]
arr1=np.array(data1)

In [4]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

# 第二种

In [5]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.zeros((3,3))#里面有括号

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones(10)#功能类似

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# 第三种

In [8]:
np.arange(15).reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])