In [1]:
import numpy as np

In [3]:
arry1=np.arange(15).reshape((3,5))

In [4]:
arry1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
arry2=np.array([1,2,3,4,5])

In [6]:
arry2

array([1, 2, 3, 4, 5])

In [7]:
arry1+arry2

array([[ 1,  3,  5,  7,  9],
       [ 6,  8, 10, 12, 14],
       [11, 13, 15, 17, 19]])

**当行数不足时，将会将第一行复制相应行数，补齐之后将进行相应运算**

In [14]:
arry3=np.array([[1],[2],[3]])

In [15]:
arry3

array([[1],
       [2],
       [3]])

In [16]:
arry1+arry3

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17]])

**列数不够时亦执行此操作**