In [1]:
import numpy as np

np.where函数有三个参数，当第一个参数为真则采取第二个参数，否则为第三个参数
类似于x if condition else y

In [2]:
arr=np.random.randn(4,4)

In [3]:
arr

array([[-1.29882595,  0.53273624, -0.85086194,  0.26133163],
       [-1.23428112, -0.40449802, -0.77633294, -0.61970672],
       [-0.25628485, -0.38574754, -0.06053012, -1.00112528],
       [-1.5397722 , -1.66642501, -1.04624326,  0.55196943]])

In [4]:
arr>0

array([[False,  True, False,  True],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True]])

In [5]:
np.where(arr>0,2,-1)

array([[-1,  2, -1,  2],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1,  2]])

这个函数将大于零的数字全都换为2，其他为-1